version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - certificates:/app/certificates
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - FILE_ENCRYPTION_KEY=cGZ/wm8jB2S6Fw19UuawMEnU7Unpt40a93EwkldlmaE=
      - SECRET_KEY=django-insecure-your-secret-key-here
      - DJANGO_SETTINGS_MODULE=core.settings

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - certificates:/app/certificates
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=https://localhost:8000
    depends_on:
      - backend

volumes:
  certificates: 